set_property IOSTANDARD LVCMOS33 [get_ports {RxData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[0]}]
set_property PACKAGE_PIN W5 [get_ports Clk]
set_property PACKAGE_PIN U18 [get_ports Rst_n]

set_property PACKAGE_PIN N17 [get_ports Rx]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports Rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports Rx]

set_property PACKAGE_PIN U16 [get_ports {RxData[0]}]
set_property PACKAGE_PIN E19 [get_ports {RxData[1]}]
set_property PACKAGE_PIN U19 [get_ports {RxData[2]}]
set_property PACKAGE_PIN V19 [get_ports {RxData[3]}]
set_property PACKAGE_PIN W18 [get_ports {RxData[4]}]
set_property PACKAGE_PIN U15 [get_ports {RxData[5]}]
set_property PACKAGE_PIN U14 [get_ports {RxData[6]}]
set_property PACKAGE_PIN V14 [get_ports {RxData[7]}]





set_property CFGBVS Vcco [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]


set_property IOSTANDARD LVCMOS33 [get_ports {count_Rx[7]}]
set_property PACKAGE_PIN L1 [get_ports {count_Rx[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count_Rx[6]}]
set_property PACKAGE_PIN P1 [get_ports {count_Rx[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count_Rx[5]}]
set_property PACKAGE_PIN N3 [get_ports {count_Rx[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count_Rx[4]}]
set_property PACKAGE_PIN P3 [get_ports {count_Rx[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count_Rx[3]}]
set_property PACKAGE_PIN U3 [get_ports {count_Rx[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count_Rx[2]}]
set_property PACKAGE_PIN W3 [get_ports {count_Rx[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count_Rx[1]}]
set_property PACKAGE_PIN V3 [get_ports {count_Rx[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count_Rx[0]}]
set_property PACKAGE_PIN V13 [get_ports {count_Rx[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {motor_signal_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {motor_signal_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {motor_signal_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {motor_signal_out[0]}]
set_property PACKAGE_PIN L17 [get_ports {motor_signal_out[0]}]
set_property PACKAGE_PIN M19 [get_ports {motor_signal_out[1]}]
set_property PACKAGE_PIN P17 [get_ports {motor_signal_out[2]}]
set_property PACKAGE_PIN R18 [get_ports {motor_signal_out[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {motor_signal_out2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {motor_signal_out2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {motor_signal_out2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {motor_signal_out2[0]}]
set_property PACKAGE_PIN N1 [get_ports {motor_signal_out2[0]}]
set_property PACKAGE_PIN M1 [get_ports {motor_signal_out2[1]}]
set_property PACKAGE_PIN M3 [get_ports {motor_signal_out2[2]}]
set_property PACKAGE_PIN K3 [get_ports {motor_signal_out2[3]}]
